apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongodb-backup
spec:
  schedule: "0 2 * * *" # Runs every day at 2 AM
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: bitnami/mongodb:latest
            command:
            - /bin/sh
            - -c
            - mongodump --host=mongodb.default.svc.cluster.local --out=/backups/mongo-backup-$(date +\%Y-\%m-\%d)
            volumeMounts:
            - name: backup-volume
              mountPath: /backups
          volumes:
          - name: backup-volume
            persistentVolumeClaim:
              claimName: mongo-backup-pvc
          restartPolicy: OnFailure